### ISSUE TITLE
Permission to add mapbox to list of companies using neon

### ISSUE THREAD

**Issue by amilajack** [mapbox/node-fuzzy-phrase#19]
We have recently rewritten the neon website from scratch and added new docs ([take a look here](https://neon-bindings.com)). We would like to add mapbox to our list of companies and projects that use neon. Are the collaborators of this project okay with that?

**Comment by kathleenlu09** [comment]
Hi @amilajack! Can you point us to a mock-up of the list companies so we can see what it would look like?

**Comment by kathleenlu09** [comment]
@amilajack Would you be able to post a screenshot from staging so that we can confirm it looks okay?

**Comment by amilajack** [comment]
Sure

<img width="1260" alt="screen shot 2018-12-14 at 2 53 01 pm" src="https://user-images.githubusercontent.com/6374832/50034064-ffc10680-ffaf-11e8-998a-9da019632352.png">

**Comment by kathleenlu09** [comment]
Thanks @amilajack! Could you please use the full logo from https://www.mapbox.com/about/press/brand-guidelines/ instead of just the icon?
Otherwise looks 👍

**Comment by amilajack** [comment]
Fixed this. Thanks.
